name: develops-today-test-case

services:
  develops-today-node:
    image: node:20
    container_name: develops-today-node
    env_file: .env
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '${APP_PORT}:${APP_PORT}'
    command: sh -c "npm install && npm run migration:up && npm run build && npm run start:dev"
    networks:
      - app-network

  develops-today-postgres:
    container_name: develops-today-postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d/
    entrypoint: >
      sh -c "chmod +x /docker-entrypoint-initdb.d/init-db.sh && exec docker-entrypoint.sh postgres"
    ports:
      - "5432:5432"
    env_file: .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: {}